name: CI

env:
  AWS_REGION: eu-north-1

on:
  push:
    branches:
      - main

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
    - name: testing
      run: echo "hello world"

    - name: aws ver
      run: aws --version

    - name: Update pack
      run: |
        sudo apt-get update
        
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Move appspec.yml to dist
      run: mv appspec.yml dist/
      
    - name: Display build output
      run: ls -l dist

    - name: Zip the dist folder
      run: cd dist && zip -r ../dist.zip *

    - name: Display all
      run: ls

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Upload to S3
      run: |
        aws s3 cp dist.zip s3://testfront111/dist.zip

    - name: Install Serve globally
      run: npm install -g serve

    - name: Start the application with Serve
      run: |
        serve -s dist -l 3000 &
        
    - name: Test application functionality (post-deployment)
      run: |
        echo "Running API tests"
        # Replace with your actual API endpoint test
        curl -s http://localhost:3000 | grep "OK" || exit 1
        echo "API is up and running"
